"""Re-exports of every public proto message and enum class.

The Python proto runtime keeps generated code under :mod:`transcodely.v1` —
import a module like ``from transcodely.v1 import drm_pb2`` and you get
``drm_pb2.DRMConfig``. That works but is verbose.

This module surfaces the same classes (and the enum constants people actually
type) at flatter paths so application code can do::

    from transcodely.types import DRMConfig, DRMSystem
    from transcodely.types import DRM_SYSTEM_WIDEVINE

For the headline types you can also import directly from :mod:`transcodely`::

    from transcodely import OutputSpec, VideoVariant, JobStatus

Enum values are also accepted as simplified strings on the wire — e.g.
``"widevine"`` instead of ``DRM_SYSTEM_WIDEVINE`` — when constructing dicts
that go through the resource helpers' ``fill_from_dict`` path.
"""

# Common: pagination, errors, codec/format/quality enums.
# API keys.
from transcodely.v1.api_key_pb2 import (
    APIKey,
    CreateAPIKeyRequest,
    CreateAPIKeyResponse,
    GetAPIKeyRequest,
    GetAPIKeyResponse,
    ListAPIKeysRequest,
    ListAPIKeysResponse,
    RevokeAPIKeyRequest,
)

# Apps.
from transcodely.v1.app_pb2 import (
    App,
    AppStatus,
    ArchiveAppRequest,
    AutoProfileDefaults,
    CreateAppRequest,
    CreateAppResponse,
    EnableHostingRequest,
    EnableHostingResponse,
    GetAppRequest,
    GetAppResponse,
    GetSpendRequest,
    GetSpendResponse,
    HostingConfig,
    ListAppsRequest,
    ListAppsResponse,
    UpdateAppRequest,
    UpdateAppResponse,
    UpdateHostingConfigRequest,
    UpdateHostingConfigResponse,
    UpdateSpendLimitRequest,
    UpdateSpendLimitResponse,
)

# Billing. Read through ``client.billing``, which needs a dashboard session
# token for an organization owner plus ``organization_id`` — an API key is
# scoped to one app, while an invoice settles a whole organization, so API keys
# are rejected.
from transcodely.v1.billing_pb2 import (
    GetInvoiceRequest,
    GetInvoiceResponse,
    GetUpcomingInvoiceRequest,
    GetUpcomingInvoiceResponse,
    Invoice,
    InvoiceLineItem,
    InvoiceLineType,
    InvoiceStatus,
    ListInvoicesRequest,
    ListInvoicesResponse,
)
from transcodely.v1.codec_av1_pb2 import AV1Options
from transcodely.v1.codec_h264_pb2 import H264Options
from transcodely.v1.codec_h265_pb2 import H265Options
from transcodely.v1.codec_vp9_pb2 import VP9Options
from transcodely.v1.common_pb2 import (
    AudioCodec,
    BitrateMode,
    Container,
    ContentType,
    DeliveryFormat,
    ErrorDetails,
    OutputFormat,
    PaginationRequest,
    PaginationResponse,
    QualityTier,
    Resolution,
    VideoCodec,
)

# Content-aware encoding is currently unavailable: the API rejects any job
# create request that sets ``content_aware`` (per-title or auto-ABR) on an
# output with InvalidArgument — rule ``parameter_unsupported`` on
# ``outputs[i].content_aware`` — until worker support ships. These types stay
# re-exported for forward compatibility.
# See https://github.com/transcodely/api/issues/167.
from transcodely.v1.content_aware_pb2 import (
    AutoABRConfig,
    ContentAnalysis,
    ContentAwareConfig,
    ContentAwareMode,
)

# Feature configs.
from transcodely.v1.drm_pb2 import (
    BYOKConfig,
    DRMConfig,
    DRMSystem,
    EncryptionScheme,
)
from transcodely.v1.drm_pb2 import KeyServerConfig as DRMKeyServerConfig
from transcodely.v1.hdr_pb2 import (
    HDRConfig,
    HDRFormat,
    HDRMode,
    ToneMapping,
)

# Health.
from transcodely.v1.health_pb2 import (
    ComponentHealth,
    HealthCheckRequest,
    HealthCheckResponse,
)

# Jobs.
from transcodely.v1.job_pb2 import (
    AudioTrackConfig,
    CancelJobRequest,
    CancelJobResponse,
    ClipConfig,
    ConfirmJobRequest,
    ConfirmJobResponse,
    CreateJobRequest,
    CreateJobResponse,
    DASHConfig,
    ExecutionTiming,
    GetJobRequest,
    GetJobResponse,
    HLSConfig,
    Job,
    JobFee,
    JobOutput,
    JobPriority,
    JobStatus,
    ListJobsRequest,
    ListJobsResponse,
    OutputSpec,
    OutputStatus,
    OutputVariantResult,
    PricingSnapshot,
    SegmentConfig,
    VariantPricingSnapshot,
    VideoVariant,
    WatchEventType,
    WatchJobRequest,
    WatchJobResponse,
)
from transcodely.v1.media_pb2 import (
    AudioStreamInfo,
    InputMetadata,
    SubtitleStreamInfo,
    VideoStreamInfo,
)

# Memberships.
from transcodely.v1.membership_pb2 import (
    GetMembershipRequest,
    GetMembershipResponse,
    ListMembershipsRequest,
    ListMembershipsResponse,
    Membership,
    MembershipRole,
    MembershipWithUser,
    RemoveMembershipRequest,
    UpdateMembershipRoleRequest,
    UpdateMembershipRoleResponse,
)

# Organizations.
from transcodely.v1.organization_pb2 import (
    CheckSlugRequest,
    CheckSlugResponse,
    CreateOrganizationRequest,
    CreateOrganizationResponse,
    GetOrganizationRequest,
    GetOrganizationResponse,
    ListOrganizationsRequest,
    ListOrganizationsResponse,
    Organization,
    UpdateOrganizationRequest,
    UpdateOrganizationResponse,
)

# Origins.
from transcodely.v1.origin_pb2 import (
    ArchiveOriginRequest,
    CreateOriginRequest,
    CreateOriginResponse,
    GcsCredentials,
    GcsOriginConfig,
    GetOriginRequest,
    GetOriginResponse,
    HttpCredentials,
    HttpOriginConfig,
    ListOriginsRequest,
    ListOriginsResponse,
    Origin,
    OriginPermission,
    OriginProvider,
    OriginRef,
    OriginStatus,
    R2Jurisdiction,
    R2OriginConfig,
    S3Credentials,
    S3OriginConfig,
    UpdateOriginRequest,
    UpdateOriginResponse,
    ValidateOriginRequest,
    ValidateOriginResponse,
    ValidationResult,
)

# Presets.
from transcodely.v1.preset_pb2 import (
    ArchivePresetRequest,
    AudioSettings,
    CreatePresetRequest,
    CreatePresetResponse,
    DuplicatePresetRequest,
    DuplicatePresetResponse,
    GetPresetBySlugRequest,
    GetPresetBySlugResponse,
    GetPresetRequest,
    GetPresetResponse,
    ListPresetsRequest,
    ListPresetsResponse,
    Preset,
    PresetVariant,
    UpdatePresetRequest,
    UpdatePresetResponse,
    VideoSettings,
)
from transcodely.v1.streaming_pb2 import (
    GOPAlignmentMode,
    HLSPlaylistType,
    HLSSegmentFormat,
    StreamingConfig,
)
from transcodely.v1.subtitles_pb2 import (
    BurnInStyle,
    ChapterPoint,
    ChapterResult,
    SubtitleFormat,
    SubtitleOperation,
    SubtitleResult,
    SubtitleTrack,
)
from transcodely.v1.thumbnails_pb2 import (
    ThumbnailFormat,
    ThumbnailMode,
    ThumbnailResult,
    ThumbnailSpec,
)

# Users.
from transcodely.v1.user_pb2 import (
    GetMeRequest,
    GetMeResponse,
    GetUserRequest,
    GetUserResponse,
    ListUsersRequest,
    ListUsersResponse,
    UpdateMeRequest,
    UpdateMeResponse,
    User,
    UserOrganization,
    UserWithOrganizations,
)

# Videos.
from transcodely.v1.video_pb2 import (
    AbortMultipartUploadRequest,
    CompletedPart,
    CompleteMultipartUploadRequest,
    CompleteMultipartUploadResponse,
    CompleteUploadRequest,
    CompleteUploadResponse,
    CreateFromUrlRequest,
    CreateFromUrlResponse,
    CreateMultipartUploadRequest,
    CreateMultipartUploadResponse,
    CreateUploadRequest,
    CreateUploadResponse,
    DailyUsage,
    DeleteVideoRequest,
    GetStatsRequest,
    GetStatsResponse,
    GetUploadPartUrlsRequest,
    GetUploadPartUrlsResponse,
    GetUsageRequest,
    GetUsageResponse,
    GetVideoRequest,
    GetVideoResponse,
    ListTopVideosRequest,
    ListTopVideosResponse,
    ListVideosRequest,
    ListVideosResponse,
    TopVideo,
    UpdateVideoRequest,
    UpdateVideoResponse,
    UploadPart,
    UsageSummary,
    Video,
    VideoRendition,
    VideoStatsDay,
    VideoStatsTotals,
    VideoStatus,
    VideoTextTrack,
    VideoVisibility,
    WatchVideoRequest,
    WatchVideoResponse,
)
from transcodely.v1.watermark_pb2 import (
    WatermarkAnchor,
    WatermarkConfig,
    WatermarkPixelPlacement,
)

# Webhooks. The proto ``Event`` (wire shape) is intentionally not surfaced here —
# the customer-facing event is the unified ``Event`` dataclass below; reach the
# raw proto via ``transcodely.v1.webhook_pb2.Event`` if you really need it.
from transcodely.v1.webhook_pb2 import (
    CreateWebhookEndpointRequest,
    CreateWebhookEndpointResponse,
    DeleteWebhookEndpointRequest,
    DeleteWebhookEndpointResponse,
    EndpointHealthSummary,
    GetEndpointHealthRequest,
    GetEndpointHealthResponse,
    HealthBucket,
    ListEventsRequest,
    ListEventsResponse,
    ListWebhookDeliveriesRequest,
    ListWebhookDeliveriesResponse,
    ListWebhookEndpointsRequest,
    ListWebhookEndpointsResponse,
    ResendEventRequest,
    ResendEventResponse,
    RetrieveEventRequest,
    RetrieveEventResponse,
    RetrieveWebhookEndpointRequest,
    RetrieveWebhookEndpointResponse,
    RotateWebhookSecretRequest,
    RotateWebhookSecretResponse,
    SendTestWebhookRequest,
    SendTestWebhookResponse,
    UpdateWebhookEndpointRequest,
    UpdateWebhookEndpointResponse,
    WebhookDelivery,
    WebhookEndpoint,
)

# The unified customer-facing event types (shared by ``construct_event`` and the
# ``client.events`` resource bridge).
from .webhooks import Event, EventRequest, EventType, WebhookEvent

__all__ = [
    "APIKey",
    "AV1Options",
    "AbortMultipartUploadRequest",
    "App",
    "AppStatus",
    "ArchiveAppRequest",
    "ArchiveOriginRequest",
    "ArchivePresetRequest",
    "AudioCodec",
    "AudioSettings",
    "AudioStreamInfo",
    "AudioTrackConfig",
    "AutoABRConfig",
    "AutoProfileDefaults",
    "BYOKConfig",
    "BitrateMode",
    "BurnInStyle",
    "CancelJobRequest",
    "CancelJobResponse",
    "ChapterPoint",
    "ChapterResult",
    "CheckSlugRequest",
    "CheckSlugResponse",
    "ClipConfig",
    "CompleteMultipartUploadRequest",
    "CompleteMultipartUploadResponse",
    "CompleteUploadRequest",
    "CompleteUploadResponse",
    "CompletedPart",
    "ComponentHealth",
    "ConfirmJobRequest",
    "ConfirmJobResponse",
    "Container",
    "ContentAnalysis",
    "ContentAwareConfig",
    "ContentAwareMode",
    "ContentType",
    "CreateAPIKeyRequest",
    "CreateAPIKeyResponse",
    "CreateAppRequest",
    "CreateAppResponse",
    "CreateFromUrlRequest",
    "CreateFromUrlResponse",
    "CreateJobRequest",
    "CreateJobResponse",
    "CreateMultipartUploadRequest",
    "CreateMultipartUploadResponse",
    "CreateOrganizationRequest",
    "CreateOrganizationResponse",
    "CreateOriginRequest",
    "CreateOriginResponse",
    "CreatePresetRequest",
    "CreatePresetResponse",
    "CreateUploadRequest",
    "CreateUploadResponse",
    "CreateWebhookEndpointRequest",
    "CreateWebhookEndpointResponse",
    "DASHConfig",
    "DRMConfig",
    "DRMKeyServerConfig",
    "DRMSystem",
    "DailyUsage",
    "DeleteVideoRequest",
    "DeleteWebhookEndpointRequest",
    "DeleteWebhookEndpointResponse",
    "DeliveryFormat",
    "DuplicatePresetRequest",
    "DuplicatePresetResponse",
    "EnableHostingRequest",
    "EnableHostingResponse",
    "EncryptionScheme",
    "EndpointHealthSummary",
    "ErrorDetails",
    "Event",
    "EventRequest",
    "EventType",
    "ExecutionTiming",
    "GOPAlignmentMode",
    "GcsCredentials",
    "GcsOriginConfig",
    "GetAPIKeyRequest",
    "GetAPIKeyResponse",
    "GetAppRequest",
    "GetAppResponse",
    "GetEndpointHealthRequest",
    "GetEndpointHealthResponse",
    "GetInvoiceRequest",
    "GetInvoiceResponse",
    "GetJobRequest",
    "GetJobResponse",
    "GetMeRequest",
    "GetMeResponse",
    "GetMembershipRequest",
    "GetMembershipResponse",
    "GetOrganizationRequest",
    "GetOrganizationResponse",
    "GetOriginRequest",
    "GetOriginResponse",
    "GetPresetBySlugRequest",
    "GetPresetBySlugResponse",
    "GetPresetRequest",
    "GetPresetResponse",
    "GetSpendRequest",
    "GetSpendResponse",
    "GetStatsRequest",
    "GetStatsResponse",
    "GetUpcomingInvoiceRequest",
    "GetUpcomingInvoiceResponse",
    "GetUploadPartUrlsRequest",
    "GetUploadPartUrlsResponse",
    "GetUsageRequest",
    "GetUsageResponse",
    "GetUserRequest",
    "GetUserResponse",
    "GetVideoRequest",
    "GetVideoResponse",
    "H264Options",
    "H265Options",
    "HDRConfig",
    "HDRFormat",
    "HDRMode",
    "HLSConfig",
    "HLSPlaylistType",
    "HLSSegmentFormat",
    "HealthBucket",
    "HealthCheckRequest",
    "HealthCheckResponse",
    "HostingConfig",
    "HttpCredentials",
    "HttpOriginConfig",
    "InputMetadata",
    "Invoice",
    "InvoiceLineItem",
    "InvoiceLineType",
    "InvoiceStatus",
    "Job",
    "JobFee",
    "JobOutput",
    "JobPriority",
    "JobStatus",
    "ListAPIKeysRequest",
    "ListAPIKeysResponse",
    "ListAppsRequest",
    "ListAppsResponse",
    "ListEventsRequest",
    "ListEventsResponse",
    "ListInvoicesRequest",
    "ListInvoicesResponse",
    "ListJobsRequest",
    "ListJobsResponse",
    "ListMembershipsRequest",
    "ListMembershipsResponse",
    "ListOrganizationsRequest",
    "ListOrganizationsResponse",
    "ListOriginsRequest",
    "ListOriginsResponse",
    "ListPresetsRequest",
    "ListPresetsResponse",
    "ListTopVideosRequest",
    "ListTopVideosResponse",
    "ListUsersRequest",
    "ListUsersResponse",
    "ListVideosRequest",
    "ListVideosResponse",
    "ListWebhookDeliveriesRequest",
    "ListWebhookDeliveriesResponse",
    "ListWebhookEndpointsRequest",
    "ListWebhookEndpointsResponse",
    "Membership",
    "MembershipRole",
    "MembershipWithUser",
    "Organization",
    "Origin",
    "OriginPermission",
    "OriginProvider",
    "OriginRef",
    "OriginStatus",
    "OutputFormat",
    "OutputSpec",
    "OutputStatus",
    "OutputVariantResult",
    "PaginationRequest",
    "PaginationResponse",
    "Preset",
    "PresetVariant",
    "PricingSnapshot",
    "QualityTier",
    "R2Jurisdiction",
    "R2OriginConfig",
    "RemoveMembershipRequest",
    "ResendEventRequest",
    "ResendEventResponse",
    "Resolution",
    "RetrieveEventRequest",
    "RetrieveEventResponse",
    "RetrieveWebhookEndpointRequest",
    "RetrieveWebhookEndpointResponse",
    "RevokeAPIKeyRequest",
    "RotateWebhookSecretRequest",
    "RotateWebhookSecretResponse",
    "S3Credentials",
    "S3OriginConfig",
    "SegmentConfig",
    "SendTestWebhookRequest",
    "SendTestWebhookResponse",
    "StreamingConfig",
    "SubtitleFormat",
    "SubtitleOperation",
    "SubtitleResult",
    "SubtitleStreamInfo",
    "SubtitleTrack",
    "ThumbnailFormat",
    "ThumbnailMode",
    "ThumbnailResult",
    "ThumbnailSpec",
    "ToneMapping",
    "TopVideo",
    "UpdateAppRequest",
    "UpdateAppResponse",
    "UpdateHostingConfigRequest",
    "UpdateHostingConfigResponse",
    "UpdateMeRequest",
    "UpdateMeResponse",
    "UpdateMembershipRoleRequest",
    "UpdateMembershipRoleResponse",
    "UpdateOrganizationRequest",
    "UpdateOrganizationResponse",
    "UpdateOriginRequest",
    "UpdateOriginResponse",
    "UpdatePresetRequest",
    "UpdatePresetResponse",
    "UpdateSpendLimitRequest",
    "UpdateSpendLimitResponse",
    "UpdateVideoRequest",
    "UpdateVideoResponse",
    "UpdateWebhookEndpointRequest",
    "UpdateWebhookEndpointResponse",
    "UploadPart",
    "UsageSummary",
    "User",
    "UserOrganization",
    "UserWithOrganizations",
    "VP9Options",
    "ValidateOriginRequest",
    "ValidateOriginResponse",
    "ValidationResult",
    "VariantPricingSnapshot",
    "Video",
    "VideoCodec",
    "VideoRendition",
    "VideoSettings",
    "VideoStatsDay",
    "VideoStatsTotals",
    "VideoStatus",
    "VideoStreamInfo",
    "VideoTextTrack",
    "VideoVariant",
    "VideoVisibility",
    "WatchEventType",
    "WatchJobRequest",
    "WatchJobResponse",
    "WatchVideoRequest",
    "WatchVideoResponse",
    "WatermarkAnchor",
    "WatermarkConfig",
    "WatermarkPixelPlacement",
    "WebhookDelivery",
    "WebhookEndpoint",
    "WebhookEvent",
]
