"""Re-exports of every public proto message and enum class.

The Python proto runtime keeps generated code under :mod:`transcodely.v1` —
import a module like ``from transcodely.v1 import drm_pb2`` and you get
``drm_pb2.DRMConfig``. That works but is verbose.

This module surfaces the same classes (and the enum constants people actually
type) at flatter paths so application code can do::

    from transcodely.types import DRMConfig, DRMSystem
    from transcodely.types import DRM_SYSTEM_WIDEVINE

For the headline types you can also import directly from :mod:`transcodely`::

    from transcodely import OutputSpec, VideoVariant, JobStatus

Enum values are also accepted as simplified strings on the wire — e.g.
``"widevine"`` instead of ``DRM_SYSTEM_WIDEVINE`` — when constructing dicts
that go through the resource helpers' ``fill_from_dict`` path.
"""

# Common: pagination, errors, codec/format/quality enums.
from transcodely.v1.common_pb2 import (
    AudioCodec,
    BitrateMode,
    Container,
    ContentType,
    DeliveryFormat,
    ErrorDetails,
    OutputFormat,
    PaginationRequest,
    PaginationResponse,
    QualityTier,
    Resolution,
    VideoCodec,
)

# Jobs.
from transcodely.v1.job_pb2 import (
    AudioTrackConfig,
    CancelJobRequest,
    CancelJobResponse,
    ConfirmJobRequest,
    ConfirmJobResponse,
    CreateJobRequest,
    CreateJobResponse,
    DASHConfig,
    ExecutionTiming,
    GetJobRequest,
    GetJobResponse,
    HLSConfig,
    Job,
    JobOutput,
    JobPriority,
    JobStatus,
    ListJobsRequest,
    ListJobsResponse,
    OutputSpec,
    OutputStatus,
    OutputVariantResult,
    PricingSnapshot,
    SegmentConfig,
    VariantPricingSnapshot,
    VideoVariant,
    WatchEventType,
    WatchJobRequest,
    WatchJobResponse,
)

# Videos.
from transcodely.v1.video_pb2 import (
    AbortMultipartUploadRequest,
    CompleteMultipartUploadRequest,
    CompleteMultipartUploadResponse,
    CompletedPart,
    CompleteUploadRequest,
    CompleteUploadResponse,
    CreateMultipartUploadRequest,
    CreateMultipartUploadResponse,
    CreateUploadRequest,
    CreateUploadResponse,
    DeleteVideoRequest,
    GetUploadPartUrlsRequest,
    GetUploadPartUrlsResponse,
    GetUsageRequest,
    GetUsageResponse,
    GetVideoRequest,
    GetVideoResponse,
    ListVideosRequest,
    ListVideosResponse,
    UpdateVideoRequest,
    UpdateVideoResponse,
    UploadPart,
    UsageSummary,
    Video,
    VideoRendition,
    VideoStatus,
    VideoVisibility,
    WatchVideoRequest,
    WatchVideoResponse,
)

# Presets.
from transcodely.v1.preset_pb2 import (
    ArchivePresetRequest,
    AudioSettings,
    CreatePresetRequest,
    CreatePresetResponse,
    DuplicatePresetRequest,
    DuplicatePresetResponse,
    GetPresetBySlugRequest,
    GetPresetBySlugResponse,
    GetPresetRequest,
    GetPresetResponse,
    ListPresetsRequest,
    ListPresetsResponse,
    Preset,
    PresetVariant,
    UpdatePresetRequest,
    UpdatePresetResponse,
    VideoSettings,
)

# Origins.
from transcodely.v1.origin_pb2 import (
    ArchiveOriginRequest,
    CreateOriginRequest,
    CreateOriginResponse,
    GcsCredentials,
    GcsOriginConfig,
    GetOriginRequest,
    GetOriginResponse,
    HttpCredentials,
    HttpOriginConfig,
    ListOriginsRequest,
    ListOriginsResponse,
    Origin,
    OriginPermission,
    OriginProvider,
    OriginRef,
    OriginStatus,
    R2Jurisdiction,
    R2OriginConfig,
    S3Credentials,
    S3OriginConfig,
    UpdateOriginRequest,
    UpdateOriginResponse,
    ValidateOriginRequest,
    ValidateOriginResponse,
    ValidationResult,
)

# Apps.
from transcodely.v1.app_pb2 import (
    App,
    ArchiveAppRequest,
    AutoProfileDefaults,
    CreateAppRequest,
    CreateAppResponse,
    CreateWebhookConfig,
    EnableHostingRequest,
    EnableHostingResponse,
    GetAppRequest,
    GetAppResponse,
    HostingConfig,
    ListAppsRequest,
    ListAppsResponse,
    UpdateAppRequest,
    UpdateAppResponse,
    UpdateHostingConfigRequest,
    UpdateHostingConfigResponse,
    UpdateWebhookConfig,
    WebhookConfig,
)

# API keys.
from transcodely.v1.api_key_pb2 import (
    APIKey,
    CreateAPIKeyRequest,
    CreateAPIKeyResponse,
    GetAPIKeyRequest,
    GetAPIKeyResponse,
    ListAPIKeysRequest,
    ListAPIKeysResponse,
    RevokeAPIKeyRequest,
)

# Organizations.
from transcodely.v1.organization_pb2 import (
    CheckSlugRequest,
    CheckSlugResponse,
    CreateOrganizationRequest,
    CreateOrganizationResponse,
    GetOrganizationRequest,
    GetOrganizationResponse,
    ListOrganizationsRequest,
    ListOrganizationsResponse,
    Organization,
    UpdateOrganizationRequest,
    UpdateOrganizationResponse,
)

# Memberships.
from transcodely.v1.membership_pb2 import (
    GetMembershipRequest,
    GetMembershipResponse,
    ListMembershipsRequest,
    ListMembershipsResponse,
    Membership,
    MembershipRole,
    MembershipWithUser,
    RemoveMembershipRequest,
    UpdateMembershipRoleRequest,
    UpdateMembershipRoleResponse,
)

# Users.
from transcodely.v1.user_pb2 import (
    GetMeRequest,
    GetMeResponse,
    GetUserRequest,
    GetUserResponse,
    ListUsersRequest,
    ListUsersResponse,
    UpdateMeRequest,
    UpdateMeResponse,
    User,
    UserOrganization,
    UserWithOrganizations,
)

# Health.
from transcodely.v1.health_pb2 import (
    ComponentHealth,
    HealthCheckRequest,
    HealthCheckResponse,
)

# Feature configs.
from transcodely.v1.drm_pb2 import (
    BYOKConfig,
    DRMConfig,
    DRMSystem,
    EncryptionScheme,
)
from transcodely.v1.drm_pb2 import KeyServerConfig as DRMKeyServerConfig

from transcodely.v1.hdr_pb2 import (
    HDRConfig,
    HDRFormat,
    HDRMode,
    ToneMapping,
)

from transcodely.v1.content_aware_pb2 import (
    AutoABRConfig,
    ContentAnalysis,
    ContentAwareConfig,
    ContentAwareMode,
)

from transcodely.v1.subtitles_pb2 import (
    BurnInStyle,
    SubtitleFormat,
    SubtitleOperation,
    SubtitleTrack,
)

from transcodely.v1.thumbnails_pb2 import (
    ThumbnailFormat,
    ThumbnailMode,
    ThumbnailResult,
    ThumbnailSpec,
)

from transcodely.v1.streaming_pb2 import (
    GOPAlignmentMode,
    HLSPlaylistType,
    HLSSegmentFormat,
    StreamingConfig,
)

from transcodely.v1.media_pb2 import (
    AudioStreamInfo,
    InputMetadata,
    SubtitleStreamInfo,
    VideoStreamInfo,
)

from transcodely.v1.codec_h264_pb2 import H264Options
from transcodely.v1.codec_h265_pb2 import H265Options
from transcodely.v1.codec_vp9_pb2 import VP9Options
from transcodely.v1.codec_av1_pb2 import AV1Options

__all__ = [
    "AbortMultipartUploadRequest",
    "APIKey",
    "App",
    "ArchiveAppRequest",
    "ArchiveOriginRequest",
    "ArchivePresetRequest",
    "AudioCodec",
    "AudioSettings",
    "AudioStreamInfo",
    "AudioTrackConfig",
    "AutoABRConfig",
    "AutoProfileDefaults",
    "AV1Options",
    "BitrateMode",
    "BurnInStyle",
    "BYOKConfig",
    "CancelJobRequest",
    "CancelJobResponse",
    "CheckSlugRequest",
    "CheckSlugResponse",
    "CompleteMultipartUploadRequest",
    "CompleteMultipartUploadResponse",
    "CompletedPart",
    "CompleteUploadRequest",
    "CompleteUploadResponse",
    "ComponentHealth",
    "ConfirmJobRequest",
    "ConfirmJobResponse",
    "Container",
    "ContentAnalysis",
    "ContentAwareConfig",
    "ContentAwareMode",
    "ContentType",
    "CreateAPIKeyRequest",
    "CreateAPIKeyResponse",
    "CreateAppRequest",
    "CreateAppResponse",
    "CreateJobRequest",
    "CreateJobResponse",
    "CreateMultipartUploadRequest",
    "CreateMultipartUploadResponse",
    "CreateOrganizationRequest",
    "CreateOrganizationResponse",
    "CreateOriginRequest",
    "CreateOriginResponse",
    "CreatePresetRequest",
    "CreatePresetResponse",
    "CreateUploadRequest",
    "CreateUploadResponse",
    "CreateWebhookConfig",
    "DASHConfig",
    "DeleteVideoRequest",
    "DeliveryFormat",
    "DRMConfig",
    "DRMKeyServerConfig",
    "DRMSystem",
    "DuplicatePresetRequest",
    "DuplicatePresetResponse",
    "EnableHostingRequest",
    "EnableHostingResponse",
    "EncryptionScheme",
    "ErrorDetails",
    "ExecutionTiming",
    "GcsCredentials",
    "GcsOriginConfig",
    "GetAPIKeyRequest",
    "GetAPIKeyResponse",
    "GetAppRequest",
    "GetAppResponse",
    "GetJobRequest",
    "GetJobResponse",
    "GetMembershipRequest",
    "GetMembershipResponse",
    "GetMeRequest",
    "GetMeResponse",
    "GetOrganizationRequest",
    "GetOrganizationResponse",
    "GetOriginRequest",
    "GetOriginResponse",
    "GetPresetBySlugRequest",
    "GetPresetBySlugResponse",
    "GetPresetRequest",
    "GetPresetResponse",
    "GetUploadPartUrlsRequest",
    "GetUploadPartUrlsResponse",
    "GetUsageRequest",
    "GetUsageResponse",
    "GetUserRequest",
    "GetUserResponse",
    "GetVideoRequest",
    "GetVideoResponse",
    "GOPAlignmentMode",
    "H264Options",
    "H265Options",
    "HDRConfig",
    "HDRFormat",
    "HDRMode",
    "HealthCheckRequest",
    "HealthCheckResponse",
    "HLSConfig",
    "HLSPlaylistType",
    "HLSSegmentFormat",
    "HostingConfig",
    "HttpCredentials",
    "HttpOriginConfig",
    "InputMetadata",
    "Job",
    "JobOutput",
    "JobPriority",
    "JobStatus",
    "ListAPIKeysRequest",
    "ListAPIKeysResponse",
    "ListAppsRequest",
    "ListAppsResponse",
    "ListJobsRequest",
    "ListJobsResponse",
    "ListMembershipsRequest",
    "ListMembershipsResponse",
    "ListOrganizationsRequest",
    "ListOrganizationsResponse",
    "ListOriginsRequest",
    "ListOriginsResponse",
    "ListPresetsRequest",
    "ListPresetsResponse",
    "ListUsersRequest",
    "ListUsersResponse",
    "ListVideosRequest",
    "ListVideosResponse",
    "Membership",
    "MembershipRole",
    "MembershipWithUser",
    "Organization",
    "Origin",
    "OriginPermission",
    "OriginProvider",
    "OriginRef",
    "OriginStatus",
    "OutputFormat",
    "OutputSpec",
    "OutputStatus",
    "OutputVariantResult",
    "PaginationRequest",
    "PaginationResponse",
    "Preset",
    "PresetVariant",
    "PricingSnapshot",
    "QualityTier",
    "R2Jurisdiction",
    "R2OriginConfig",
    "RemoveMembershipRequest",
    "Resolution",
    "RevokeAPIKeyRequest",
    "S3Credentials",
    "S3OriginConfig",
    "SegmentConfig",
    "StreamingConfig",
    "SubtitleFormat",
    "SubtitleOperation",
    "SubtitleStreamInfo",
    "SubtitleTrack",
    "ThumbnailFormat",
    "ThumbnailMode",
    "ThumbnailResult",
    "ThumbnailSpec",
    "ToneMapping",
    "UpdateAppRequest",
    "UpdateAppResponse",
    "UpdateHostingConfigRequest",
    "UpdateHostingConfigResponse",
    "UpdateMembershipRoleRequest",
    "UpdateMembershipRoleResponse",
    "UpdateMeRequest",
    "UpdateMeResponse",
    "UpdateOrganizationRequest",
    "UpdateOrganizationResponse",
    "UpdateOriginRequest",
    "UpdateOriginResponse",
    "UpdatePresetRequest",
    "UpdatePresetResponse",
    "UpdateVideoRequest",
    "UpdateVideoResponse",
    "UpdateWebhookConfig",
    "UploadPart",
    "UsageSummary",
    "User",
    "UserOrganization",
    "UserWithOrganizations",
    "ValidateOriginRequest",
    "ValidateOriginResponse",
    "ValidationResult",
    "VariantPricingSnapshot",
    "Video",
    "VideoCodec",
    "VideoRendition",
    "VideoSettings",
    "VideoStatus",
    "VideoStreamInfo",
    "VideoVariant",
    "VideoVisibility",
    "VP9Options",
    "WatchEventType",
    "WatchJobRequest",
    "WatchJobResponse",
    "WatchVideoRequest",
    "WatchVideoResponse",
    "WebhookConfig",
]
