# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/codec_vp9.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/codec_vp9.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etranscodely/v1/codec_vp9.proto\x12\x0etranscodely.v1\x1a\x1b\x62uf/validate/validate.proto\"\xc1\x04\n\nVP9Options\x12(\n\x07profile\x18\x01 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x03(\x00H\x00R\x07profile\x88\x01\x01\x12&\n\x07quality\x18\x02 \x01(\tB\x07\xbaH\x04r\x02\x18\x14H\x01R\x07quality\x88\x01\x01\x12 \n\x03\x63rf\x18\x03 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18?(\x00H\x02R\x03\x63rf\x88\x01\x01\x12$\n\x05speed\x18\x04 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x08(\x00H\x03R\x05speed\x88\x01\x01\x12*\n\x07\x62itrate\x18\x05 \x01(\x05\x42\x0b\xbaH\x08\x1a\x06\x18\xf0\x93\t(dH\x04R\x07\x62itrate\x88\x01\x01\x12\x31\n\x0bmin_bitrate\x18\x06 \x01(\x05\x42\x0b\xbaH\x08\x1a\x06\x18\xf0\x93\t(dH\x05R\nminBitrate\x88\x01\x01\x12\x31\n\x0bmax_bitrate\x18\x07 \x01(\x05\x42\x0b\xbaH\x08\x1a\x06\x18\xf0\x93\t(dH\x06R\nmaxBitrate\x88\x01\x01\x12\'\n\x06keyint\x18\x08 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\xd8\x04(\x01H\x07R\x06keyint\x88\x01\x01\x12\x31\n\x0ctile_columns\x18\t \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x06(\x00H\x08R\x0btileColumns\x88\x01\x01\x12+\n\ttile_rows\x18\n \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x02(\x00H\tR\x08tileRows\x88\x01\x01\x42\n\n\x08_profileB\n\n\x08_qualityB\x06\n\x04_crfB\x08\n\x06_speedB\n\n\x08_bitrateB\x0e\n\x0c_min_bitrateB\x0e\n\x0c_max_bitrateB\t\n\x07_keyintB\x0f\n\r_tile_columnsB\x0c\n\n_tile_rowsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.codec_vp9_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['profile']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['profile']._serialized_options = b'\272H\006\032\004\030\003(\000'
  _globals['_VP9OPTIONS'].fields_by_name['quality']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['quality']._serialized_options = b'\272H\004r\002\030\024'
  _globals['_VP9OPTIONS'].fields_by_name['crf']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['crf']._serialized_options = b'\272H\006\032\004\030?(\000'
  _globals['_VP9OPTIONS'].fields_by_name['speed']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['speed']._serialized_options = b'\272H\006\032\004\030\010(\000'
  _globals['_VP9OPTIONS'].fields_by_name['bitrate']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['bitrate']._serialized_options = b'\272H\010\032\006\030\360\223\t(d'
  _globals['_VP9OPTIONS'].fields_by_name['min_bitrate']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['min_bitrate']._serialized_options = b'\272H\010\032\006\030\360\223\t(d'
  _globals['_VP9OPTIONS'].fields_by_name['max_bitrate']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['max_bitrate']._serialized_options = b'\272H\010\032\006\030\360\223\t(d'
  _globals['_VP9OPTIONS'].fields_by_name['keyint']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['keyint']._serialized_options = b'\272H\007\032\005\030\330\004(\001'
  _globals['_VP9OPTIONS'].fields_by_name['tile_columns']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['tile_columns']._serialized_options = b'\272H\006\032\004\030\006(\000'
  _globals['_VP9OPTIONS'].fields_by_name['tile_rows']._loaded_options = None
  _globals['_VP9OPTIONS'].fields_by_name['tile_rows']._serialized_options = b'\272H\006\032\004\030\002(\000'
  _globals['_VP9OPTIONS']._serialized_start=80
  _globals['_VP9OPTIONS']._serialized_end=657
# @@protoc_insertion_point(module_scope)
