# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/codec_av1.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/codec_av1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etranscodely/v1/codec_av1.proto\x12\x0etranscodely.v1\x1a\x1b\x62uf/validate/validate.proto\"\xb6\x05\n\nAV1Options\x12&\n\x06preset\x18\x01 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\r(\x00H\x00R\x06preset\x88\x01\x01\x12\"\n\x04tune\x18\x02 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x01(\x00H\x01R\x04tune\x88\x01\x01\x12 \n\x03\x63rf\x18\x03 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18?(\x00H\x02R\x03\x63rf\x88\x01\x01\x12*\n\x07\x62itrate\x18\x04 \x01(\x05\x42\x0b\xbaH\x08\x1a\x06\x18\xa0\x8d\x06(dH\x03R\x07\x62itrate\x88\x01\x01\x12\x31\n\x0bmax_bitrate\x18\x05 \x01(\x05\x42\x0b\xbaH\x08\x1a\x06\x18\xa0\x8d\x06(dH\x04R\nmaxBitrate\x88\x01\x01\x12\'\n\x06keyint\x18\x06 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\xd8\x04(\x01H\x05R\x06keyint\x88\x01\x01\x12\x31\n\x0ctile_columns\x18\x07 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x04(\x00H\x06R\x0btileColumns\x88\x01\x01\x12+\n\ttile_rows\x18\x08 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x04(\x00H\x07R\x08tileRows\x88\x01\x01\x12-\n\nfilm_grain\x18\t \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x32(\x00H\x08R\tfilmGrain\x88\x01\x01\x12\"\n\nenable_dlf\x18\n \x01(\x08H\tR\tenableDlf\x88\x01\x01\x12$\n\x0b\x65nable_cdef\x18\x0b \x01(\x08H\nR\nenableCdef\x88\x01\x01\x12\x32\n\x12\x65nable_restoration\x18\x0c \x01(\x08H\x0bR\x11\x65nableRestoration\x88\x01\x01\x42\t\n\x07_presetB\x07\n\x05_tuneB\x06\n\x04_crfB\n\n\x08_bitrateB\x0e\n\x0c_max_bitrateB\t\n\x07_keyintB\x0f\n\r_tile_columnsB\x0c\n\n_tile_rowsB\r\n\x0b_film_grainB\r\n\x0b_enable_dlfB\x0e\n\x0c_enable_cdefB\x15\n\x13_enable_restorationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.codec_av1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['preset']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['preset']._serialized_options = b'\272H\006\032\004\030\r(\000'
  _globals['_AV1OPTIONS'].fields_by_name['tune']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['tune']._serialized_options = b'\272H\006\032\004\030\001(\000'
  _globals['_AV1OPTIONS'].fields_by_name['crf']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['crf']._serialized_options = b'\272H\006\032\004\030?(\000'
  _globals['_AV1OPTIONS'].fields_by_name['bitrate']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['bitrate']._serialized_options = b'\272H\010\032\006\030\240\215\006(d'
  _globals['_AV1OPTIONS'].fields_by_name['max_bitrate']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['max_bitrate']._serialized_options = b'\272H\010\032\006\030\240\215\006(d'
  _globals['_AV1OPTIONS'].fields_by_name['keyint']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['keyint']._serialized_options = b'\272H\007\032\005\030\330\004(\001'
  _globals['_AV1OPTIONS'].fields_by_name['tile_columns']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['tile_columns']._serialized_options = b'\272H\006\032\004\030\004(\000'
  _globals['_AV1OPTIONS'].fields_by_name['tile_rows']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['tile_rows']._serialized_options = b'\272H\006\032\004\030\004(\000'
  _globals['_AV1OPTIONS'].fields_by_name['film_grain']._loaded_options = None
  _globals['_AV1OPTIONS'].fields_by_name['film_grain']._serialized_options = b'\272H\006\032\004\0302(\000'
  _globals['_AV1OPTIONS']._serialized_start=80
  _globals['_AV1OPTIONS']._serialized_end=774
# @@protoc_insertion_point(module_scope)
