# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/content_aware.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/content_aware.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2
from transcodely.v1 import common_pb2 as transcodely_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"transcodely/v1/content_aware.proto\x12\x0etranscodely.v1\x1a\x1b\x62uf/validate/validate.proto\x1a\x1btranscodely/v1/common.proto\"\xb1\x02\n\rAutoABRConfig\x12\x31\n\x0cmin_variants\x18\x01 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x14(\x02H\x00R\x0bminVariants\x88\x01\x01\x12\x31\n\x0cmax_variants\x18\x02 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x14(\x02H\x01R\x0bmaxVariants\x88\x01\x01\x12K\n\x0emin_resolution\x18\x03 \x01(\x0e\x32\x1a.transcodely.v1.ResolutionB\x08\xbaH\x05\x82\x01\x02\x10\x01R\rminResolution\x12K\n\x0emax_resolution\x18\x04 \x01(\x0e\x32\x1a.transcodely.v1.ResolutionB\x08\xbaH\x05\x82\x01\x02\x10\x01R\rmaxResolutionB\x0f\n\r_min_variantsB\x0f\n\r_max_variants\"\xf2\x01\n\x12\x43ontentAwareConfig\x12\x41\n\x04mode\x18\x01 \x01(\x0e\x32 .transcodely.v1.ContentAwareModeB\x0b\xbaH\x08\x82\x01\x02\x10\x01\xc8\x01\x01R\x04mode\x12=\n\x0bvmaf_target\x18\x02 \x01(\x01\x42\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\xc0X@)\x00\x00\x00\x00\x00\x80Q@H\x00R\nvmafTarget\x88\x01\x01\x12=\n\x08\x61uto_abr\x18\x03 \x01(\x0b\x32\x1d.transcodely.v1.AutoABRConfigH\x01R\x07\x61utoAbr\x88\x01\x01\x42\x0e\n\x0c_vmaf_targetB\x0b\n\t_auto_abr\"\xa7\x01\n\x0f\x43ontentAnalysis\x12)\n\x10\x63omplexity_score\x18\x01 \x01(\x01R\x0f\x63omplexityScore\x12!\n\x0cmotion_score\x18\x02 \x01(\x01R\x0bmotionScore\x12#\n\rtexture_score\x18\x03 \x01(\x01R\x0ctextureScore\x12!\n\x0c\x63ontent_type\x18\x04 \x01(\tR\x0b\x63ontentType*y\n\x10\x43ontentAwareMode\x12\"\n\x1e\x43ONTENT_AWARE_MODE_UNSPECIFIED\x10\x00\x12 \n\x1c\x43ONTENT_AWARE_MODE_PER_TITLE\x10\x01\x12\x1f\n\x1b\x43ONTENT_AWARE_MODE_AUTO_ABR\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.content_aware_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTOABRCONFIG'].fields_by_name['min_variants']._loaded_options = None
  _globals['_AUTOABRCONFIG'].fields_by_name['min_variants']._serialized_options = b'\272H\006\032\004\030\024(\002'
  _globals['_AUTOABRCONFIG'].fields_by_name['max_variants']._loaded_options = None
  _globals['_AUTOABRCONFIG'].fields_by_name['max_variants']._serialized_options = b'\272H\006\032\004\030\024(\002'
  _globals['_AUTOABRCONFIG'].fields_by_name['min_resolution']._loaded_options = None
  _globals['_AUTOABRCONFIG'].fields_by_name['min_resolution']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_AUTOABRCONFIG'].fields_by_name['max_resolution']._loaded_options = None
  _globals['_AUTOABRCONFIG'].fields_by_name['max_resolution']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_CONTENTAWARECONFIG'].fields_by_name['mode']._loaded_options = None
  _globals['_CONTENTAWARECONFIG'].fields_by_name['mode']._serialized_options = b'\272H\010\202\001\002\020\001\310\001\001'
  _globals['_CONTENTAWARECONFIG'].fields_by_name['vmaf_target']._loaded_options = None
  _globals['_CONTENTAWARECONFIG'].fields_by_name['vmaf_target']._serialized_options = b'\272H\024\022\022\031\000\000\000\000\000\300X@)\000\000\000\000\000\200Q@'
  _globals['_CONTENTAWAREMODE']._serialized_start=835
  _globals['_CONTENTAWAREMODE']._serialized_end=956
  _globals['_AUTOABRCONFIG']._serialized_start=113
  _globals['_AUTOABRCONFIG']._serialized_end=418
  _globals['_CONTENTAWARECONFIG']._serialized_start=421
  _globals['_CONTENTAWARECONFIG']._serialized_end=663
  _globals['_CONTENTANALYSIS']._serialized_start=666
  _globals['_CONTENTANALYSIS']._serialized_end=833
# @@protoc_insertion_point(module_scope)
