# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/hdr.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/hdr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18transcodely/v1/hdr.proto\x12\x0etranscodely.v1\x1a\x1b\x62uf/validate/validate.proto\"\xef\x03\n\tHDRConfig\x12;\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x19.transcodely.v1.HDRFormatB\x08\xbaH\x05\x82\x01\x02\x10\x01R\x06\x66ormat\x12\x38\n\x04mode\x18\x02 \x01(\x0e\x32\x17.transcodely.v1.HDRModeB\x0b\xbaH\x08\x82\x01\x02\x10\x01\xc8\x01\x01R\x04mode\x12H\n\x0ctone_mapping\x18\x03 \x01(\x0e\x32\x1b.transcodely.v1.ToneMappingB\x08\xbaH\x05\x82\x01\x02\x10\x01R\x0btoneMapping\x12\x39\n\x10target_peak_nits\x18\x04 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\x90N(dH\x00R\x0etargetPeakNits\x88\x01\x01\x12\x34\n\x0emaster_display\x18\x05 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x02H\x01R\rmasterDisplay\x88\x01\x01\x12<\n\x13\x63ontent_light_level\x18\x06 \x01(\tB\x07\xbaH\x04r\x02\x18@H\x02R\x11\x63ontentLightLevel\x88\x01\x01\x12&\n\x07rpu_url\x18\x07 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10H\x03R\x06rpuUrl\x88\x01\x01\x42\x13\n\x11_target_peak_nitsB\x11\n\x0f_master_displayB\x16\n\x14_content_light_levelB\n\n\x08_rpu_url*\xaa\x01\n\tHDRFormat\x12\x1a\n\x16HDR_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n\x10HDR_FORMAT_HDR10\x10\x01\x12\x19\n\x15HDR_FORMAT_HDR10_PLUS\x10\x02\x12\x12\n\x0eHDR_FORMAT_HLG\x10\x03\x12\x1d\n\x19HDR_FORMAT_DOLBY_VISION_5\x10\x04\x12\x1d\n\x19HDR_FORMAT_DOLBY_VISION_8\x10\x05*g\n\x07HDRMode\x12\x18\n\x14HDR_MODE_UNSPECIFIED\x10\x00\x12\x18\n\x14HDR_MODE_PASSTHROUGH\x10\x01\x12\x14\n\x10HDR_MODE_TONEMAP\x10\x02\x12\x12\n\x0eHDR_MODE_FORCE\x10\x03*\x90\x01\n\x0bToneMapping\x12\x1c\n\x18TONE_MAPPING_UNSPECIFIED\x10\x00\x12\x19\n\x15TONE_MAPPING_REINHARD\x10\x01\x12\x16\n\x12TONE_MAPPING_HABLE\x10\x02\x12\x17\n\x13TONE_MAPPING_BT2390\x10\x03\x12\x17\n\x13TONE_MAPPING_MOBIUS\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.hdr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['format']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['format']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_HDRCONFIG'].fields_by_name['mode']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['mode']._serialized_options = b'\272H\010\202\001\002\020\001\310\001\001'
  _globals['_HDRCONFIG'].fields_by_name['tone_mapping']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['tone_mapping']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_HDRCONFIG'].fields_by_name['target_peak_nits']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['target_peak_nits']._serialized_options = b'\272H\007\032\005\030\220N(d'
  _globals['_HDRCONFIG'].fields_by_name['master_display']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['master_display']._serialized_options = b'\272H\005r\003\030\200\002'
  _globals['_HDRCONFIG'].fields_by_name['content_light_level']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['content_light_level']._serialized_options = b'\272H\004r\002\030@'
  _globals['_HDRCONFIG'].fields_by_name['rpu_url']._loaded_options = None
  _globals['_HDRCONFIG'].fields_by_name['rpu_url']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_HDRFORMAT']._serialized_start=572
  _globals['_HDRFORMAT']._serialized_end=742
  _globals['_HDRMODE']._serialized_start=744
  _globals['_HDRMODE']._serialized_end=847
  _globals['_TONEMAPPING']._serialized_start=850
  _globals['_TONEMAPPING']._serialized_end=994
  _globals['_HDRCONFIG']._serialized_start=74
  _globals['_HDRCONFIG']._serialized_end=569
# @@protoc_insertion_point(module_scope)
