# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/health.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btranscodely/v1/health.proto\x12\x0etranscodely.v1\"?\n\x12HealthCheckRequest\x12\x1d\n\x07service\x18\x01 \x01(\tH\x00R\x07service\x88\x01\x01\x42\n\n\x08_service\"\xa6\x01\n\x13HealthCheckResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32\x1c.transcodely.v1.HealthStatusR\x06status\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12?\n\ncomponents\x18\x03 \x03(\x0b\x32\x1f.transcodely.v1.ComponentHealthR\ncomponents\"\x86\x01\n\x0f\x43omponentHealth\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x34\n\x06status\x18\x02 \x01(\x0e\x32\x1c.transcodely.v1.HealthStatusR\x06status\x12\x1d\n\x07message\x18\x03 \x01(\tH\x00R\x07message\x88\x01\x01\x42\n\n\x08_message*\x81\x01\n\x0cHealthStatus\x12\x1d\n\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1a\n\x16HEALTH_STATUS_DEGRADED\x10\x02\x12\x1b\n\x17HEALTH_STATUS_UNHEALTHY\x10\x03\x32\x61\n\rHealthService\x12P\n\x05\x43heck\x12\".transcodely.v1.HealthCheckRequest\x1a#.transcodely.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHSTATUS']._serialized_start=419
  _globals['_HEALTHSTATUS']._serialized_end=548
  _globals['_HEALTHCHECKREQUEST']._serialized_start=47
  _globals['_HEALTHCHECKREQUEST']._serialized_end=110
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=113
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=279
  _globals['_COMPONENTHEALTH']._serialized_start=282
  _globals['_COMPONENTHEALTH']._serialized_end=416
  _globals['_HEALTHSERVICE']._serialized_start=550
  _globals['_HEALTHSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
