# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transcodely/v1/watermark.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'transcodely/v1/watermark.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etranscodely/v1/watermark.proto\x12\x0etranscodely.v1\x1a\x1b\x62uf/validate/validate.proto\"i\n\x17WatermarkPixelPlacement\x12\x15\n\x01x\x18\x01 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\x01x\x12\x15\n\x01y\x18\x02 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00R\x01y\x12 \n\x05width\x18\x03 \x01(\x05\x42\n\xbaH\x07\x1a\x05\x18\x80< \x00R\x05width\"\xc4\x03\n\x0fWatermarkConfig\x12\x37\n\timage_url\x18\x01 \x01(\tB\x1a\xbaH\x17r\x12\x18\x80\x10\x32\r^https?://.*$\xc8\x01\x01R\x08imageUrl\x12\x46\n\x06\x61nchor\x18\x02 \x01(\x0e\x32\x1f.transcodely.v1.WatermarkAnchorB\x08\xbaH\x05\x82\x01\x02\x10\x01H\x00R\x06\x61nchor\x88\x01\x01\x12\x39\n\twidth_pct\x18\x03 \x01(\x01\x42\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00Y@!\x00\x00\x00\x00\x00\x00\x00\x00H\x01R\x08widthPct\x88\x01\x01\x12;\n\nmargin_pct\x18\x04 \x01(\x01\x42\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\x44@)\x00\x00\x00\x00\x00\x00\x00\x00H\x02R\tmarginPct\x88\x01\x01\x12\x36\n\x07opacity\x18\x05 \x01(\x01\x42\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?!\x00\x00\x00\x00\x00\x00\x00\x00H\x03R\x07opacity\x88\x01\x01\x12\x42\n\x05pixel\x18\x06 \x01(\x0b\x32\'.transcodely.v1.WatermarkPixelPlacementH\x04R\x05pixel\x88\x01\x01\x42\t\n\x07_anchorB\x0c\n\n_width_pctB\r\n\x0b_margin_pctB\n\n\x08_opacityB\x08\n\x06_pixel*\xe5\x02\n\x0fWatermarkAnchor\x12 \n\x1cWATERMARK_ANCHOR_UNSPECIFIED\x10\x00\x12\x1d\n\x19WATERMARK_ANCHOR_TOP_LEFT\x10\x01\x12\x1f\n\x1bWATERMARK_ANCHOR_TOP_CENTER\x10\x02\x12\x1e\n\x1aWATERMARK_ANCHOR_TOP_RIGHT\x10\x03\x12 \n\x1cWATERMARK_ANCHOR_MIDDLE_LEFT\x10\x04\x12\"\n\x1eWATERMARK_ANCHOR_MIDDLE_CENTER\x10\x05\x12!\n\x1dWATERMARK_ANCHOR_MIDDLE_RIGHT\x10\x06\x12 \n\x1cWATERMARK_ANCHOR_BOTTOM_LEFT\x10\x07\x12\"\n\x1eWATERMARK_ANCHOR_BOTTOM_CENTER\x10\x08\x12!\n\x1dWATERMARK_ANCHOR_BOTTOM_RIGHT\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transcodely.v1.watermark_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['x']._loaded_options = None
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['x']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['y']._loaded_options = None
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['y']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['width']._loaded_options = None
  _globals['_WATERMARKPIXELPLACEMENT'].fields_by_name['width']._serialized_options = b'\272H\007\032\005\030\200< \000'
  _globals['_WATERMARKCONFIG'].fields_by_name['image_url']._loaded_options = None
  _globals['_WATERMARKCONFIG'].fields_by_name['image_url']._serialized_options = b'\272H\027r\022\030\200\0202\r^https?://.*$\310\001\001'
  _globals['_WATERMARKCONFIG'].fields_by_name['anchor']._loaded_options = None
  _globals['_WATERMARKCONFIG'].fields_by_name['anchor']._serialized_options = b'\272H\005\202\001\002\020\001'
  _globals['_WATERMARKCONFIG'].fields_by_name['width_pct']._loaded_options = None
  _globals['_WATERMARKCONFIG'].fields_by_name['width_pct']._serialized_options = b'\272H\024\022\022\031\000\000\000\000\000\000Y@!\000\000\000\000\000\000\000\000'
  _globals['_WATERMARKCONFIG'].fields_by_name['margin_pct']._loaded_options = None
  _globals['_WATERMARKCONFIG'].fields_by_name['margin_pct']._serialized_options = b'\272H\024\022\022\031\000\000\000\000\000\000D@)\000\000\000\000\000\000\000\000'
  _globals['_WATERMARKCONFIG'].fields_by_name['opacity']._loaded_options = None
  _globals['_WATERMARKCONFIG'].fields_by_name['opacity']._serialized_options = b'\272H\024\022\022\031\000\000\000\000\000\000\360?!\000\000\000\000\000\000\000\000'
  _globals['_WATERMARKANCHOR']._serialized_start=642
  _globals['_WATERMARKANCHOR']._serialized_end=999
  _globals['_WATERMARKPIXELPLACEMENT']._serialized_start=79
  _globals['_WATERMARKPIXELPLACEMENT']._serialized_end=184
  _globals['_WATERMARKCONFIG']._serialized_start=187
  _globals['_WATERMARKCONFIG']._serialized_end=639
# @@protoc_insertion_point(module_scope)
